# Generated by Django 3.0.8 on 2021-02-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodels',
            name='otp',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
