# Generated by Django 3.0.8 on 2021-02-18 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_usermodels_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodels',
            name='otp',
        ),
        migrations.CreateModel(
            name='UserModelsWithoutOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=1000)),
                ('contact', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=5000)),
                ('password', models.CharField(max_length=5000)),
                ('otp', models.CharField(default='', max_length=10000)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
