# Generated by Django 3.0.8 on 2021-02-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210218_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorsapplied',
            name='pay',
        ),
        migrations.AlterField(
            model_name='usermodelswithoutotp',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
