# Generated by Django 3.0.8 on 2021-02-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210218_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
