# Generated by Django 3.0.8 on 2021-02-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210218_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorsapplied',
            name='name',
            field=models.CharField(max_length=2000),
        ),
    ]
