# Generated by Django 3.0.8 on 2021-02-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210216_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=100000)),
                ('slug', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
