# Generated by Django 3.0.8 on 2021-02-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_importantlinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='visits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
