# Generated by Django 3.0.8 on 2021-02-18 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_news_visits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-visits']},
        ),
    ]
